

INSERT INTO `movies` (`id`, `movieName`, `year`, `genre`, `overview`, `director`, `cast`, `imagepath`, `deleted_at`, `created_at`, `updated_at`) VALUES
(1, 'Dangal', '2024-0', 'Family Drama', 'dfsfgtsgtr', 'fhksgreg', 'dskhdshfirhf', 'https://m.media-amazon.com/images/M/MV5BZDE4YzA3MGMtNmQ1ZS00NTkzLWFkYjQtMGQ2NDlhYTU4NjgxXkEyXkFqcGdeQXVyNDI3NjU1NzQ@._V1_.jpg', '2024-08-18 14:12:37', NULL, '2024-08-18 14:12:37'),
(2, 'Gully Boy', '2019', 'Drama, Music, Romance', 'A coming-of-age story based on the lives of street rappers in Mumbai.', 'Zoya Akhtar', 'Ranveer Singh, Alia Bhatt, Siddhant Chaturvedi, Vijay Raaz', 'https://m.media-amazon.com/images/M/MV5BZDkzMTQ1YTMtMWY4Ny00MzExLTkzYzEtNzZhOTczNzU2NTU1XkEyXkFqcGdeQXVyODY3NjMyMDU@._V1_FMjpg_UX1000_.jpg', NULL, NULL, '2024-08-18 18:47:57'),
(3, 'Veere Di Wedding', '2018', 'Comedy', 'Four girls on their way to find true love discover that their friendship must remain strong until the wedding of a friend named Veer.', 'Shashanka Ghosh', 'Kareena Kapoor, Sonam Kapoor, Swara Bhasker, Shikha Talsania', 'https://m.media-amazon.com/images/M/MV5BODJjZTFkNjctMGZiMi00NjYzLWI0ZjktN2I3ZDg2MDhmZWQzXkEyXkFqcGdeQXVyMTA4NjE0NjEy._V1_.jpg', NULL, NULL, NULL),
(4, 'Tiger Zinda Hai', '2017', 'Action, Adventure, Thriller', 'Inspired by real events, Tiger Zinda Hai is a sequel to the blockbuster Ek Tha Tiger, and an espionage action drama that follows a daring rescue mission in Iraq.', 'Mehmet Tutkun, Ali Abbas Zafar, Musa Muhammed Olayinka', 'Salman Khan, Katrina Kaif, Nawab Shah, Anupriya Goenka', 'https://m.media-amazon.com/images/M/MV5BMTdlNjE5MGYtODliNy00NGI4LWExMDItYzZmMzdmM2E1ZjRkXkEyXkFqcGdeQXVyMTA4NjE0NjEy._V1_.jpg', NULL, NULL, NULL),
(5, 'Zero', '2018', 'Comedy, Drama, Romance', 'The story revolves around Bauua Singh (Shah Rukh Khan), a vertically challenged man, who is full of charm and wit, with a pinch of arrogance. Born to a wealthy family and raised in an environment of affluence, he is challenged to broaden his horizon and f', 'Aanand L. Rai', 'Shah Rukh Khan, Anushka Sharma, Katrina Kaif, Mohd. Zeeshan Ayyub', 'https://upload.wikimedia.org/wikipedia/en/e/e6/Zero_official_poster.jpg', NULL, NULL, NULL),
(6, 'Simmba', '2018', 'Action, Crime, Drama', 'Simmba, a Corrupt Officer, enjoys all the perks of being an immoral and unethical police officer until a life-changing event forces him to choose the righteous path.', 'Rohit Shetty', 'Ranveer Singh, Sara Ali Khan, Sonu Sood, Ashutosh Rana', 'https://m.media-amazon.com/images/M/MV5BMWIzNGU3ZWEtNTRjOC00OTYzLWFlZmUtMjE5NmMxMmE0MGIwXkEyXkFqcGdeQXVyNjE1OTQ0NjA@._V1_.jpg', NULL, NULL, NULL),
(7, 'Sonu Ke Titu Ki Sweety', '2018', 'Comedy, Romance', 'Titu is going to marry a perfect woman named Sweety. Titu\'s best-friend Sonu doubts Sweety\'s character and tries to break the marriage while Sweety tries to do opposite and which leads to war between Bromance and Romance.', 'Luv Ranjan', 'Kartik Aaryan, Nushrratt Bharuccha, Sunny Singh, Alok Nath', 'https://m.media-amazon.com/images/M/MV5BNmFmNGUwNTUtMTQ3OC00M2Y1LTkxOTQtOTE4MmMyNDNhZDJkXkEyXkFqcGdeQXVyMTA4NjE0NjEy._V1_.jpg', NULL, NULL, NULL),
(8, 'Dhadak', '2018', 'Drama, Romance', 'Set in Rajasthan, this love story explores how the protagonists deal with issues like differences between castes and honor killings.', 'Shashank Khaitan', 'Janhvi Kapoor, Ishaan Khattar, Ashutosh Rana, Aditya Kumar', 'https://m.media-amazon.com/images/M/MV5BNDc4YmY4ZjMtMmMxOS00ZDdhLWI3NjItMWRjZTkzNWE0NDQ5XkEyXkFqcGdeQXVyMTA4NjE0NjEy._V1_.jpg', NULL, NULL, NULL),
(9, 'Total Dhamaal', '2019', 'Action, Adventure, Comedy', 'A group of people learn about a hidden treasure and then they race to find it and claim it.', 'Indra Kumar', 'Ajay Devgn, Anil Kapoor, Madhuri Dixit, Riteish Deshmukh', 'https://m.media-amazon.com/images/M/MV5BMTdiN2Q2MGUtYWRjMi00M2Y2LWEzOTYtOTA3NjNiMGMzNmFhXkEyXkFqcGdeQXVyNjE1OTQ0NjA@._V1_.jpg', NULL, NULL, NULL),
(10, 'Batti Gul Meter Chalu', '2018', 'Drama', 'The life of three friends takes a tragic turn due to an inflated electricity bill, which leads to a courtroom drama and social awakening.', 'Shree Narayan Singh', 'Shahid Kapoor, Shraddha Kapoor, Divyendu Sharma, Yami Gautam', 'https://m.media-amazon.com/images/M/MV5BODIzZjJiYTYtYzlkMS00NzgxLWFlNTAtM2U5NjgwZTkxZmRjXkEyXkFqcGdeQXVyMTA4NjE0NjEy._V1_.jpg', NULL, NULL, NULL),
(11, 'Nawabzaade', '2018', 'Comedy, Romance', 'Three best friends fall in love with a simple, stay-at-home girl from their neighbourhood. As they all go out of their way to win her love, they are pitted against each other in their efforts.', 'Jayesh Pradhan', 'Dharmesh Yelande, Punit Pathak, Raghav Juyal, Isha Rikhi', 'https://m.media-amazon.com/images/M/MV5BMTUzNDM2Njc0N15BMl5BanBnXkFtZTgwNDg3MTE5NTM@._V1_FMjpg_UX1000_.jpg', NULL, NULL, NULL),
(12, 'Ek Ladki Ko Dekha Toh Aisa Laga', '2019', 'Comedy, Crime, Drama', 'The film tells the story of closeted lesbian Sweety Chaudhary and her attempts to come out to her conservative, traditional family.', 'Shelly Chopra Dhar', 'Sonam Kapoor, Anil Kapoor, Rajkummar Rao, Juhi Chawla', 'https://m.media-amazon.com/images/M/MV5BZTNlY2YyOGYtZWFhYy00MDc3LTliYzMtZTUyYzVlNjQxZGRjXkEyXkFqcGdeQXVyNjE1OTQ0NjA@._V1_FMjpg_UX1000_.jpg', NULL, NULL, NULL),
(13, 'Satyameva Jayate', '2018', 'Action, Crime, Drama', 'An honest cop attempts to hunt down a vigilante who kills corrupt cops by setting them on fire.', 'Milap Zaveri', 'John Abraham, Manoj Bajpayee, Aisha Sharma, Amruta Khanvilkar', 'https://m.media-amazon.com/images/M/MV5BYzk2N2U5MjQtMjBmYy00OTA4LWJkNDEtYjNhMWJlMjNmNWQxXkEyXkFqcGdeQXVyMTA4NjE0NjEy._V1_.jpg', NULL, NULL, NULL),
(14, 'Mitron', '2018', 'Comedy', 'In order to bring stability in Jai\'s life, his father decides to get him married. However, fate has other plans.', 'Nitin Kakkar', 'Jackky Bhagnani, Kritika Kamra, Prateik Patil Babbar, Perlene Bhersaina', 'https://m.media-amazon.com/images/M/MV5BYzRhNjA0NDYtYzMzMy00NDc4LTlmNzktMmZmYzFkMGQ1MDRmXkEyXkFqcGdeQXVyOTEwNTU0MDI@._V1_.jpg', NULL, NULL, NULL),
(15, 'Namaste England', '2018', 'Romance/Comedy Drama', 'A couple\'s relationship undergoes stress and changes as they struggle to fulfil their dreams of relocating to England.', 'Vipul Amrutlal Shah', 'Arjun Kapoor, Parineeti Chopra, Aditya Seal , Alankrita Sahai, Anil Mange, Satish K', 'https://m.media-amazon.com/images/M/MV5BYjRlN2M0NWUtODQxMy00NjI1LWEzNDQtMTMzMTIyM2ZiZDJmXkEyXkFqcGdeQXVyODE5NzE3OTE@._V1_.jpg', NULL, NULL, NULL),
(16, 'Luka Chuppi', '2019', 'Comedy, Romance', 'Pretending to be married in order to cohabitate, a small-town couple lands in endless awkward situations to hide the truth from their orthodox families.', 'Laxman Utekar', 'Kartik Aaryan, Kriti Sanon, Aparshakti Khurana, Pankaj Tripathi', 'https://m.media-amazon.com/images/M/MV5BY2MwM2ZhNTItMzkwNi00MTQxLTljMDAtZTk1YmU2M2YzNGVmXkEyXkFqcGdeQXVyNjE1OTQ0NjA@._V1_FMjpg_UX1000_.jpg', NULL, NULL, NULL),
(17, 'Cheat India', '2019', 'Indian Film Pop', 'Focuses on existing malpractices in country\'s education system, the whole concept of buying your way through education, jobs and earnings.', 'Soumik Sen', 'Emraan Hashmi, Shreya Dhanwanthary,\r\nShivani Bedi, Snigdhadeep Chatterjee, \r\nManuj ', 'https://m.media-amazon.com/images/M/MV5BNjkyYmYzZGEtYzkwZS00ODk0LThhYmItODg1ZThjYzFkNTZiXkEyXkFqcGdeQXVyMjUxMTY3ODM@._V1_.jpg', NULL, NULL, NULL),
(18, 'KGF', '2018', 'Action/Crime', 'The blood-soaked land of Kolar Gold Fields has a new overlord now, Rocky, whose name strikes fear in the heart of his foes. His allies look up to him as their Savior, the government sees him as a threat, and his enemies are clamouring for revenge', 'Prashanth Neel', 'Yash, Ramachandra Raju, Srinidhi Shetty,\r\nVasishta N. Simha, Achyuth Kumar, Archana', 'https://m.media-amazon.com/images/M/MV5BZDNlNzBjMGUtYTA0Yy00OTI2LWJmZjMtODliYmUyYTI0OGFmXkEyXkFqcGdeQXVyODIwMDI1NjM@._V1_FMjpg_UX1000_.jpg', NULL, NULL, NULL),
(19, 'Fraud Saiyaan', '2019', 'Comedy Drama', 'Bhola, a con artist, travels around the city wooing various women into marrying him in a bid to satisfy his monetary needs.', 'Sourabh Shrivastava', 'Arshad Warsi, Rana Bhola Pratap Singh, Mohit Balchandani, Saurabh Shukla, Flora Sai', 'https://m.media-amazon.com/images/M/MV5BMmUwYTBlZjktNmQ3Yi00MWFhLWIyNzEtYTM5MGVhMjAwN2Q5XkEyXkFqcGdeQXVyMTA4NjE0NjEy._V1_.jpg', NULL, NULL, NULL);

